import React, { useState, useRef } from 'react';
import { 
  Check, 
  Download, 
  Film, 
  Image as ImageIcon, 
  Music, 
  Play, 
  Pause, 
  Plus, 
  RotateCw, 
  Share2, 
  SlidersHorizontal, 
  Volume2, 
  X,
  Sparkles,
  ShieldCheck
} from 'lucide-react';
import { GenerationRecord } from '../../../types/aiGeneration';

interface GenerationPreviewModalProps {
  isOpen: boolean;
  onClose: () => void;
  record: GenerationRecord | null;
  onAddToMediaBin: (record: GenerationRecord) => void;
  onAddToTimeline?: (record: GenerationRecord) => void;
  onOpenInPhotoStudio?: (record: GenerationRecord) => void;
  onOpenInAudioStudio?: (record: GenerationRecord) => void;
  onRegenerate?: (record: GenerationRecord) => void;
  onCreateVariation?: (record: GenerationRecord) => void;
}

export const GenerationPreviewModal: React.FC<GenerationPreviewModalProps> = ({
  isOpen,
  onClose,
  record,
  onAddToMediaBin,
  onAddToTimeline,
  onOpenInPhotoStudio,
  onOpenInAudioStudio,
  onRegenerate,
  onCreateVariation,
}) => {
  const [isPlayingAudio, setIsPlayingAudio] = useState(false);
  const [addedToProject, setAddedToProject] = useState(false);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  if (!isOpen || !record) return null;

  const handleToggleAudio = () => {
    if (!audioRef.current) return;
    if (isPlayingAudio) {
      audioRef.current.pause();
      setIsPlayingAudio(false);
    } else {
      audioRef.current.play();
      setIsPlayingAudio(true);
    }
  };

  const handleDownload = () => {
    if (!record.outputUrl) return;
    const a = document.createElement('a');
    a.href = record.outputUrl;
    const ext = record.outputType === 'video' ? 'webm' : record.outputType === 'image' ? 'png' : 'wav';
    a.download = `ai-gen-${record.taskType}-${Date.now()}.${ext}`;
    a.click();
  };

  const handleAddToBin = () => {
    onAddToMediaBin(record);
    setAddedToProject(true);
    setTimeout(() => setAddedToProject(false), 2500);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-xs animate-in fade-in duration-150">
      <div className="w-full max-w-2xl bg-white dark:bg-[#12161f] border border-neutral-200 dark:border-neutral-800 rounded-xl shadow-2xl overflow-hidden flex flex-col text-neutral-900 dark:text-neutral-100 max-h-[90vh]">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-3.5 border-b border-neutral-200 dark:border-neutral-800 shrink-0">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-purple-500/10 dark:bg-purple-500/20 text-purple-600 dark:text-purple-400 flex items-center justify-center">
              {record.outputType === 'video' ? (
                <Film className="w-4 h-4" />
              ) : record.outputType === 'image' ? (
                <ImageIcon className="w-4 h-4" />
              ) : (
                <Music className="w-4 h-4" />
              )}
            </div>
            <div>
              <h3 className="text-sm font-semibold truncate max-w-sm">{record.title}</h3>
              <p className="text-[11px] text-neutral-500 dark:text-neutral-400">
                Generated by {record.modelName} ({record.provider})
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-md text-neutral-400 hover:text-neutral-600 dark:hover:text-neutral-200 hover:bg-neutral-100 dark:hover:bg-neutral-800"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Viewport & Player Body */}
        <div className="flex-1 overflow-y-auto p-5 space-y-4">
          {/* Main Visual Display */}
          <div className="relative rounded-lg overflow-hidden bg-neutral-950 flex items-center justify-center min-h-[260px] border border-neutral-800">
            {record.outputType === 'video' && record.outputUrl && (
              <video
                src={record.outputUrl}
                controls
                autoPlay
                loop
                className="max-h-[380px] w-full object-contain rounded-md"
              />
            )}

            {record.outputType === 'image' && record.outputUrl && (
              <img
                src={record.outputUrl}
                alt={record.prompt}
                className="max-h-[380px] w-full object-contain rounded-md"
              />
            )}

            {record.outputType === 'audio' && record.outputUrl && (
              <div className="w-full p-8 flex flex-col items-center justify-center space-y-5">
                <audio
                  ref={audioRef}
                  src={record.outputUrl}
                  onEnded={() => setIsPlayingAudio(false)}
                />
                <button
                  onClick={handleToggleAudio}
                  className="w-16 h-16 rounded-full bg-purple-600 hover:bg-purple-500 text-white flex items-center justify-center shadow-lg transition-transform active:scale-95"
                >
                  {isPlayingAudio ? <Pause className="w-7 h-7" /> : <Play className="w-7 h-7 ml-1" />}
                </button>
                <div className="w-full max-w-md space-y-2">
                  <div className="h-10 bg-neutral-900 rounded flex items-center justify-center px-4 gap-1">
                    {/* Visual audio bars simulation */}
                    {Array.from({ length: 32 }).map((_, i) => (
                      <div
                        key={i}
                        className={`w-1 rounded-full transition-all duration-150 ${
                          isPlayingAudio ? 'bg-purple-500 animate-pulse' : 'bg-neutral-700'
                        }`}
                        style={{
                          height: isPlayingAudio ? `${Math.sin(i * 0.8) * 16 + 18}px` : '8px',
                        }}
                      />
                    ))}
                  </div>
                  <div className="flex items-center justify-between text-xs text-neutral-400 font-mono">
                    <span>48kHz / 24-bit Stereo Master</span>
                    <span>{record.durationSec || 4}s Duration</span>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Multiple image variations carousel if available */}
          {record.outputUrls && record.outputUrls.length > 1 && (
            <div className="space-y-1.5">
              <div className="text-xs font-semibold text-neutral-500 dark:text-neutral-400">Variations Batch:</div>
              <div className="flex gap-2 overflow-x-auto pb-1">
                {record.outputUrls.map((url, idx) => (
                  <img
                    key={idx}
                    src={url}
                    alt={`Variation ${idx + 1}`}
                    className="w-20 h-20 rounded-md object-cover border border-neutral-700 hover:border-purple-500 cursor-pointer transition-colors shrink-0"
                    onClick={() => {
                      record.outputUrl = url;
                    }}
                  />
                ))}
              </div>
            </div>
          )}

          {/* Metadata Cards */}
          <div className="p-3.5 rounded-lg bg-neutral-50 dark:bg-neutral-900/50 border border-neutral-200 dark:border-neutral-800 space-y-2 text-xs">
            <div>
              <span className="text-neutral-500 dark:text-neutral-400 font-medium">Prompt:</span>
              <p className="font-mono text-neutral-800 dark:text-neutral-200 mt-0.5 leading-relaxed bg-white dark:bg-neutral-950 p-2 rounded border border-neutral-200 dark:border-neutral-800">
                “{record.prompt}”
              </p>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 pt-2 border-t border-neutral-200 dark:border-neutral-800/60 font-mono text-[11px]">
              <div>
                <span className="text-neutral-400">Model:</span>
                <div className="font-semibold truncate">{record.modelName.split(' ')[0]}</div>
              </div>
              <div>
                <span className="text-neutral-400">Ratio / Res:</span>
                <div className="font-semibold">{record.aspectRatio || '16:9'} ({record.resolution || '1080p'})</div>
              </div>
              <div>
                <span className="text-neutral-400">Credits Used:</span>
                <div className="font-semibold text-purple-600 dark:text-purple-400">{record.creditsDeducted} CR</div>
              </div>
              <div>
                <span className="text-neutral-400">License:</span>
                <div className="font-semibold flex items-center gap-1 text-emerald-600 dark:text-emerald-400">
                  <ShieldCheck className="w-3 h-3" />
                  <span>Commercial</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="flex flex-wrap items-center justify-between gap-2.5 px-5 py-3.5 border-t border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-[#0c0f16] shrink-0">
          <div className="flex items-center gap-2">
            {onRegenerate && (
              <button
                onClick={() => onRegenerate(record)}
                className="px-2.5 py-1.5 rounded-lg border border-neutral-300 dark:border-neutral-700 text-xs font-medium hover:bg-neutral-100 dark:hover:bg-neutral-800 flex items-center gap-1.5 transition-colors"
                title="Regenerate with same settings"
              >
                <RotateCw className="w-3.5 h-3.5" />
                <span>Regenerate</span>
              </button>
            )}

            {onCreateVariation && (
              <button
                onClick={() => onCreateVariation(record)}
                className="px-2.5 py-1.5 rounded-lg border border-neutral-300 dark:border-neutral-700 text-xs font-medium hover:bg-neutral-100 dark:hover:bg-neutral-800 flex items-center gap-1.5 transition-colors"
                title="Create a variation of this output"
              >
                <SlidersHorizontal className="w-3.5 h-3.5" />
                <span>Variation</span>
              </button>
            )}

            <button
              onClick={handleDownload}
              className="px-2.5 py-1.5 rounded-lg border border-neutral-300 dark:border-neutral-700 text-xs font-medium hover:bg-neutral-100 dark:hover:bg-neutral-800 flex items-center gap-1.5 transition-colors"
              title="Download file to device"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Save File</span>
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleAddToBin}
              disabled={addedToProject}
              className={`px-3.5 py-1.5 rounded-lg text-xs font-medium border flex items-center gap-1.5 transition-all ${
                addedToProject
                  ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-600'
                  : 'border-neutral-300 dark:border-neutral-700 hover:bg-neutral-100 dark:hover:bg-neutral-800'
              }`}
            >
              {addedToProject ? <Check className="w-3.5 h-3.5" /> : <Plus className="w-3.5 h-3.5" />}
              <span>{addedToProject ? 'Added to Media Bin' : 'Add to Media Bin'}</span>
            </button>

            {/* Destination Specific Shortcut */}
            {record.outputType === 'video' && onAddToTimeline && (
              <button
                onClick={() => onAddToTimeline(record)}
                className="px-3.5 py-1.5 rounded-lg bg-neutral-900 dark:bg-white text-white dark:text-neutral-950 text-xs font-medium hover:opacity-90 flex items-center gap-1.5 shadow-sm"
              >
                <Film className="w-3.5 h-3.5" />
                <span>Add to Timeline</span>
              </button>
            )}

            {record.outputType === 'image' && onOpenInPhotoStudio && (
              <button
                onClick={() => onOpenInPhotoStudio(record)}
                className="px-3.5 py-1.5 rounded-lg bg-neutral-900 dark:bg-white text-white dark:text-neutral-950 text-xs font-medium hover:opacity-90 flex items-center gap-1.5 shadow-sm"
              >
                <ImageIcon className="w-3.5 h-3.5" />
                <span>Open in Photo Studio</span>
              </button>
            )}

            {record.outputType === 'audio' && onOpenInAudioStudio && (
              <button
                onClick={() => onOpenInAudioStudio(record)}
                className="px-3.5 py-1.5 rounded-lg bg-neutral-900 dark:bg-white text-white dark:text-neutral-950 text-xs font-medium hover:opacity-90 flex items-center gap-1.5 shadow-sm"
              >
                <Music className="w-3.5 h-3.5" />
                <span>Send to Audio Studio</span>
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
