import { AIToolMeta, PhotoAIToolId, VideoAIToolId } from '../../types/aiTools';

export const PHOTO_AI_TOOLS: AIToolMeta[] = [
  {
    id: 'photo_bg_removal',
    name: 'Background Removal',
    category: 'photo',
    shortDescription: 'High-precision subject cutout with alpha edge feathering & manual refinement.',
    fullDescription: 'Isolates foreground subjects using neural salient contour detection with interactive brush refinement (add/remove, feather, edge refinement) and transparent PNG export.',
    capability: 'image',
    defaultModelId: 'gemini-3.8-flash',
    costCredits: 2,
    isProOnly: false,
    supportedInputTypes: ['image'],
    badge: 'Popular',
  },
  {
    id: 'photo_bg_replace',
    name: 'Background Replace',
    category: 'photo',
    shortDescription: 'Swap backgrounds with solid colors, custom images, or generative prompts.',
    fullDescription: 'Separates foreground subject and positions them seamlessly over new solid color, uploaded plate, or AI synthesized backdrop with scale and positioning controls.',
    capability: 'image',
    defaultModelId: 'gemini-3.8-flash',
    costCredits: 3,
    isProOnly: false,
    supportedInputTypes: ['image'],
  },
  {
    id: 'photo_object_removal',
    name: 'Object Removal',
    category: 'photo',
    shortDescription: 'Brush over unwanted elements for context-aware texture synthesis inpainting.',
    fullDescription: 'Erase pedestrians, powerlines, blemishes, or objects with an interactive brush mask. Replaces the region using content-aware texture synthesis.',
    capability: 'image',
    defaultModelId: 'gemini-3.8-flash',
    costCredits: 2,
    isProOnly: false,
    supportedInputTypes: ['image'],
    badge: 'Core',
  },
  {
    id: 'photo_object_replace',
    name: 'Object Replacement',
    category: 'photo',
    shortDescription: 'Brush over any item and describe what to replace it with.',
    fullDescription: 'Select an object mask and specify replacement instructions (e.g. "Replace coffee cup with vintage camera"). Synthesizes a matching replacement matching lighting.',
    capability: 'image',
    defaultModelId: 'flux-1.1-pro',
    costCredits: 4,
    isProOnly: true,
    supportedInputTypes: ['image'],
    requiresExternalProvider: true,
    requiredProviderName: 'Flux / BFL',
  },
  {
    id: 'photo_gen_fill',
    name: 'Generative Fill',
    category: 'photo',
    shortDescription: 'Synthesize photorealistic elements into any selected region.',
    fullDescription: 'Paint a marquee or lasso region and enter an optional instruction. Generates contextually coherent elements adhering to perspective and grain.',
    capability: 'image',
    defaultModelId: 'gemini-3.8-flash',
    costCredits: 3,
    isProOnly: false,
    supportedInputTypes: ['image'],
  },
  {
    id: 'photo_gen_expand',
    name: 'Generative Expand',
    category: 'photo',
    shortDescription: 'Expand canvas aspect ratio (1:1, 4:5, 9:16, 16:9) with outpainting.',
    fullDescription: 'Expands the outer boundaries of an image to fill modern aspect ratios. Synthesizes seamless background continuation without stretching the subject.',
    capability: 'image',
    defaultModelId: 'gemini-3.8-flash',
    costCredits: 3,
    isProOnly: false,
    supportedInputTypes: ['image'],
  },
  {
    id: 'photo_upscale',
    name: 'Image Upscale',
    category: 'photo',
    shortDescription: '2× / 4× neural super-resolution with micro-texture recovery.',
    fullDescription: 'Upscales low-resolution photos with edge reconstruction, unsharp masking, and fine pixel synthesis for print and 4K displays.',
    capability: 'upscaling',
    defaultModelId: 'gemini-3.8-flash',
    costCredits: 3,
    isProOnly: false,
    supportedInputTypes: ['image'],
    badge: 'HD',
  },
  {
    id: 'photo_enhance',
    name: 'Image Enhancement',
    category: 'photo',
    shortDescription: 'Automated dynamic range, detail recovery, noise reduction, and clarity.',
    fullDescription: 'Multi-point tonal enhancement removing digital grain, balancing shadow clipping, and bringing pop to muted photography.',
    capability: 'image',
    defaultModelId: 'creative-director-local',
    costCredits: 1,
    isProOnly: false,
    supportedInputTypes: ['image'],
  },
  {
    id: 'photo_portrait_enhance',
    name: 'Face & Portrait Enhance',
    category: 'photo',
    shortDescription: 'Natural skin smoothing, iris sharpening, dental whitening & eye catchlights.',
    fullDescription: 'Detects facial landmarks to gently clarify skin textures, enhance gaze sharpness, and eliminate lens chromatic distortion.',
    capability: 'image',
    defaultModelId: 'gemini-3.8-flash',
    costCredits: 2,
    isProOnly: false,
    supportedInputTypes: ['image'],
  },
  {
    id: 'photo_relight',
    name: 'AI Relight',
    category: 'photo',
    shortDescription: 'Studio lighting simulation: warm, cool, soft, studio, and directional beams.',
    fullDescription: 'Re-illuminates 2D photos using estimated surface normal maps. Adjust light position, elevation, and warmth non-destructively.',
    capability: 'image',
    defaultModelId: 'creative-director-local',
    costCredits: 2,
    isProOnly: false,
    supportedInputTypes: ['image'],
  },
  {
    id: 'photo_restoration',
    name: 'Old Photo Restoration',
    category: 'photo',
    shortDescription: 'Repair creases, scratches, dust tears, and film grain degradation.',
    fullDescription: 'Neural inpainting and structural restoration for archived family and historical photographs. Erases physical tear lines and water damage.',
    capability: 'image',
    defaultModelId: 'gemini-3.8-flash',
    costCredits: 3,
    isProOnly: true,
    supportedInputTypes: ['image'],
  },
  {
    id: 'photo_colorize',
    name: 'Colorize',
    category: 'photo',
    shortDescription: 'Restore authentic historical colors to monochrome & vintage B&W photos.',
    fullDescription: 'Detects period clothing, foliage, skin tones, and sky hues to synthesize photorealistic, naturalistic color palettes for monochrome pictures.',
    capability: 'image',
    defaultModelId: 'gemini-3.8-flash',
    costCredits: 2,
    isProOnly: false,
    supportedInputTypes: ['image'],
  },
  {
    id: 'photo_image_gen',
    name: 'AI Image Generation',
    category: 'photo',
    shortDescription: 'Text-to-image synthesis with ratio, quality, negative prompt & variations.',
    fullDescription: 'State-of-the-art visual generation directly into your project bin or as a fresh layer. Choose aspect ratios, negative directives, and variations.',
    capability: 'image',
    defaultModelId: 'gemini-3.8-flash',
    costCredits: 4,
    isProOnly: false,
    supportedInputTypes: ['image'],
    badge: 'Pro Grade',
  },
  {
    id: 'photo_img2img',
    name: 'Image-to-Image',
    category: 'photo',
    shortDescription: 'Transform existing imagery with creative prompts and adjustable strength.',
    fullDescription: 'Re-renders an input photo into new stylistic representations (anime, cyberpunk, watercolor, 3D render) while preserving core composition geometry.',
    capability: 'image',
    defaultModelId: 'gemini-3.8-flash',
    costCredits: 3,
    isProOnly: false,
    supportedInputTypes: ['image'],
  },
];

export const VIDEO_AI_TOOLS: AIToolMeta[] = [
  {
    id: 'video_bg_removal',
    name: 'Video Background Removal',
    category: 'video',
    shortDescription: 'Extract foreground video subjects into transparent alpha clips without green screen.',
    fullDescription: 'Performs temporal neural rotoscoping across motion frames. Outputs an alpha-channel clip ready for compositing over graphic tracks.',
    capability: 'vfx',
    defaultModelId: 'runway-gen3-alpha',
    costCredits: 8,
    isProOnly: true,
    supportedInputTypes: ['video'],
    requiresExternalProvider: true,
    requiredProviderName: 'Runway Gen-3',
    badge: 'Pro VFX',
  },
  {
    id: 'video_object_removal',
    name: 'Video Object Removal',
    category: 'video',
    shortDescription: 'Track and inpaint moving objects or unwanted passersby across video clips.',
    fullDescription: 'Select an object box in the scrubber and track its optical flow vector. Erases the object across the sequence using temporal background stitching.',
    capability: 'vfx',
    defaultModelId: 'runway-gen3-alpha',
    costCredits: 8,
    isProOnly: true,
    supportedInputTypes: ['video'],
    requiresExternalProvider: true,
    requiredProviderName: 'Runway Gen-3',
  },
  {
    id: 'video_object_replace',
    name: 'Video Object Replacement',
    category: 'video',
    shortDescription: 'Track objects in motion and replace with generative 3D visual elements.',
    fullDescription: 'Combines optical flow tracking with neural diffusion. Preserves perspective, camera blur, and lighting interaction across the timeline.',
    capability: 'vfx',
    defaultModelId: 'runway-gen3-alpha',
    costCredits: 10,
    isProOnly: true,
    supportedInputTypes: ['video'],
    requiresExternalProvider: true,
    requiredProviderName: 'Runway Gen-3',
  },
  {
    id: 'video_enhance',
    name: 'Video Enhancement',
    category: 'video',
    shortDescription: 'Denoise, sharpen, compression artifact cleanup, and dynamic range boost.',
    fullDescription: 'Clean up compressed footage, sensor noise, and blocky streaming artifacts for broadcast-ready clarity.',
    capability: 'video',
    defaultModelId: 'creative-director-local',
    costCredits: 3,
    isProOnly: false,
    supportedInputTypes: ['video'],
    badge: 'Essential',
  },
  {
    id: 'video_upscale',
    name: 'Video Upscale',
    category: 'video',
    shortDescription: '720p / 1080p to pristine 4K video resolution with temporal consistency.',
    fullDescription: 'Enhances video resolution while maintaining frame-to-frame stability and eliminating flickering or temporal crawling.',
    capability: 'upscaling',
    defaultModelId: 'runway-gen3-alpha',
    costCredits: 8,
    isProOnly: true,
    supportedInputTypes: ['video'],
    requiresExternalProvider: true,
    requiredProviderName: 'Runway Gen-3',
  },
  {
    id: 'video_stabilization',
    name: 'Stabilization',
    category: 'video',
    shortDescription: 'Smooth out handheld camera jitter and rolling shutter vibrations.',
    fullDescription: 'Computes multi-point affine motion vectors to smooth jerky camera moves and create gimbal-like cinematic tracking.',
    capability: 'video',
    defaultModelId: 'creative-director-local',
    costCredits: 2,
    isProOnly: false,
    supportedInputTypes: ['video'],
  },
  {
    id: 'video_frame_interpolation',
    name: 'Frame Interpolation',
    category: 'video',
    shortDescription: 'Boost 24fps/30fps to buttery-smooth 60fps or fluid 120fps slow-motion.',
    fullDescription: 'Calculates bi-directional optical flow to synthesize intermediate frames without stutter or ghostly blending artifacts.',
    capability: 'video',
    defaultModelId: 'runway-gen3-alpha',
    costCredits: 6,
    isProOnly: true,
    supportedInputTypes: ['video'],
    requiresExternalProvider: true,
    requiredProviderName: 'Runway Gen-3',
  },
  {
    id: 'video_auto_reframe',
    name: 'Auto Reframe',
    category: 'video',
    shortDescription: 'Convert 16:9 widescreen to 9:16 Shorts/Reels while tracking the active subject.',
    fullDescription: 'Detects faces and prominent motion action to dynamically pan and zoom the crop box, keeping the hero in frame with manual adjustment override.',
    capability: 'video',
    defaultModelId: 'creative-director-local',
    costCredits: 2,
    isProOnly: false,
    supportedInputTypes: ['video'],
    badge: 'Popular',
  },
  {
    id: 'video_scene_detection',
    name: 'Scene Detection',
    category: 'video',
    shortDescription: 'Detect cut boundaries and split points to navigate or place timeline markers.',
    fullDescription: 'Performs frame-by-frame histogram difference analysis to identify hard cuts, dissolves, and scene shifts without deleting clips.',
    capability: 'video',
    defaultModelId: 'creative-director-local',
    costCredits: 1,
    isProOnly: false,
    supportedInputTypes: ['video'],
  },
  {
    id: 'video_auto_cut',
    name: 'Auto Cut',
    category: 'video',
    shortDescription: 'Trim silent pauses, dead air, and filler repetitions automatically.',
    fullDescription: 'Analyzes audio waveforms and speech cadence to flag or splice dead gaps, generating a tight rough cut with preview review.',
    capability: 'video',
    defaultModelId: 'creative-director-local',
    costCredits: 2,
    isProOnly: false,
    supportedInputTypes: ['video', 'audio'],
  },
  {
    id: 'video_captions',
    name: 'AI Captions',
    category: 'video',
    shortDescription: 'Speech-to-text transcript generation with custom fonts, pop animations & SRT export.',
    fullDescription: 'Generates animated word-by-word or sentence subtitles with full timing editor, typography styling (pop/fade/karaoke), and SRT/VTT file downloads.',
    capability: 'audio',
    defaultModelId: 'gemini-3.8-flash',
    costCredits: 2,
    isProOnly: false,
    supportedInputTypes: ['video', 'audio'],
    badge: 'Essential',
  },
];

export const ALL_AI_TOOLS: AIToolMeta[] = [...PHOTO_AI_TOOLS, ...VIDEO_AI_TOOLS];
export const AI_TOOLS_CATALOG = ALL_AI_TOOLS;

export function getToolMeta(toolId: string): AIToolMeta | undefined {
  return ALL_AI_TOOLS.find(t => t.id === toolId);
}
export const getAIToolById = getToolMeta;
